OrdererOrgs:
  - Name: Orderer
    Domain: orderer.com
    Specs:
      - Hostname: orderer
      
PeerOrgs:
  - Name: Org1
    Domain: org1.com
    Specs:
      - Hostname: devpeer
        CommonName: devpeer
    Users:
      Count: 2

  - Name: Org2
    Domain: org2.com
    Specs:
      - Hostname: devpeer
        CommonName: devpeer
    Users:
      Count: 2



      